### ISSUE TITLE
Should we use the HTML parser

### ISSUE THREAD

**Issue by straker** [straker/html-tagged-template#1]
The HTML parser is difficult to work with. Creating [nodes out of context](https://lists.w3.org/Archives/Public/www-dom/2011OctDec/0170.html) (such as a `<tr></tr>`) result in no returned element, and the HTML parser generates [unexpected results in many cases](https://lists.w3.org/Archives/Public/public-script-coord/2013JanMar/0290.html).

> `<image>` create an "img" element, `</br><br>` creates two "br" elements, `</p><p>` creates more "p" elements than `<p></p>`, `<table><input>` creates two siblings while `<table><input type=hidden>` creates a parent/child relationship, `<isindex prompt>` creates half a dozen nodes including multiple text nodes and elements, though none of them with the tag name "isindex", and the output even has an attribute, though it's not called "prompt", `<script>` having all kinds of wacky interactions with the event loop, crazy things happening with association of form controls to form elements, elements being literally moved in the DOM as the DOM is created... the list of crazy behaviours is long and esoteric

However, if we were to avoid the HTML parser and instead try to use an AST to generate the DOM, we would probably have to [recreate the HTML parser](http://google-caja.googlecode.com/svn-history/r528/changes/mikesamuel/string-interpolation-29-Jan-2008/trunk/src/NOT-FOR-TRUNK/interp/index.html#-autogen-id-8) in some way, shape, or form to handle misnested tags (such as `<b>A <span style="color:blue">B</b> C</span>` outputting  `<b>A <span style="color:blue">B</span></b> C`). 

Both solutions have their benefits and problems, so the question becomes which is going to be easier to work with and generate the least amount of unexpected results for the user? 

Libraries like jQuery use the [HTML parser](http://james.padolsey.com/jquery/#v=2.1.3&fn=jQuery.parseHTML) and have been for years, so maybe we should as well to coincide with what developers are already use to?

**Comment by jshcrowthe** [comment]
I would say that us trying to interpret what a developer means instead of just giving them the secured output of the HTML Parser (IMO what they'd expect) is not essential.

Alternatively if we decide that we want to mock the standard HTML parser we could try using something like [`DOMParser`](https://developer.mozilla.org/en-US/docs/Web/API/DOMParser#Browser_compatibility) which has good [browser support](http://caniuse.com/#feat=xml-serializer) as well.
