### ISSUE TITLE
Alternative

### ISSUE THREAD

**Issue by eorroe** [straker/html-tagged-template#10]
I [proposed](https://esdiscuss.org/topic/string-substitute) a method called `String.substitute()`

Which would work like the following:

```JS

var html = `<input value="${val}">`;

String.substitute(html, {
  val: 'hello'
}); // <input value="hello">
```

I think this would work much better, because this is not only for html, js now is on more and more platforms and not just the web.

Now for actual repeated markup, there is the [`<template>`](http://caniuse.com/#search=template) element, which should be extended to do the following:

```HTML
<template id="temp">
  <li>${text}</li>
</template>
<ul id="list"></ul>
```

```JS
var list = document.getElementById('list');
var temp = document.getElementById('temp');
var dataArr = [ { text: 'hello' }, { text: 'hi' }, { text: 'hey' } ];

dataArr.forEach(function(data) {
  var li = temp.parse(data); // returns a documentFragment
  list.appendChild(li);
});
```

**I think this is something that would be much better, to have an element that handles all of this Natively**

**Comment by straker** [comment]
I'm sorry, I'm not exactly sure what it is you are asking with this issue. An alternative to what exactly?

**Comment by straker** [comment]
Close due to inactivity
