### ISSUE TITLE
Should substitutionindex: really be deterministic?

### ISSUE THREAD

**Issue by mozfreddyb** [straker/html-tagged-template#11]
I couldn't come up with a nice test case, but I'm concerned about an attacker supplying something like
`<p>${xss}</p><a title="substitutionindex:0">yo</a>`

**Comment by straker** [comment]
An attacker could do `<p>${xss}</p><a title="substitutionindex:0:">yo</a>`, but this would only cause the value of `${xss}` to be placed into the title using `setAttribute`, which is almost equivalent to doing `<p>${xss}</p><a title="${xss}">yo</a>`. Even if the attacker did `<p>${xss}</p><a title="substitutionindex:10:">yo</a>`, the value of `undefined` would be placed into the title.

**Comment by mozfreddyb** [comment]
Ah yes, I was concerned that it would confuse the context-sensitive escaping when used in different contexts. But the values are escaped when before insertion and not in-place.
