### ISSUE TITLE
Windows 10 Firefox 44 shifts the attribute NamedNodeMap when using removeAttribute

### ISSUE THREAD

**Issue by straker** [straker/html-tagged-template#13]
We had a [failing test](https://travis-ci.org/straker/html-tagged-template/builds/110513628#L720) that revealed this bug, and I just confirmed it. When we loop over the attributes `NamedNodeMap` looking for substitutions, we use `removeAttribute` to remove a placeholder attribute name (`substitutionindex:1:`) with it's substitution name (`disabled`). However, in Firefox 44, using `removeAttribute` modifies the attributes `NamedNodeMap`, shifting the attribute out of the map and shifting all indexes by 1. This modification causes the for loop to skip an index so to speak, which caused the test to fail.

@domenic, @annevk is this behavior correct, or is this a bug in Firefox 44 (didn't happen in Windows 7, Firefox 43)? Do we still need to work around the behavior, possibly just keeping a list of attributes to remove after the loop is over so we don't do it in the loop?

```js
let min = 0, max = 99;
let node = html`<input min="${min}" type="number" max="${max}"/>`

for (var i = 0; i < node.attributes.length; i++) {
  console.log(node.attributes);  // => [ type="number", max="99", min="0"]; 
  node.removeAttribute('type'); 
  console.log(node.attributes);  // => [ max="99", min="0" ];
}
```

**Comment by annevk** [comment]
Most legacy DOM objects are "live" and have been forever. It seems really surprising that Firefox 43 would not do this. When I rewrite that code to

```
<!DOCTYPE html>
...<script>
let x = document.createElement("x"); x.innerHTML = '<input min="${min}" type="number" max="${max}"/>'
let node = x.firstChild

for (var i = 0; i < node.attributes.length; i++) {
  w(node.attributes);  // => [ type="number", max="99", min="0"]; 
  node.removeAttribute('type'); 
  w(node.attributes);  // => [ max="99", min="0" ];
}
</script>
```
I get the same behavior in Chrome and Firefox.

Your code does look wrong though. Why do the min and max attribute declarations not have a closing double quote?

**Comment by straker** [comment]
Sorry, that was a mistake on my part, the closing quotes should be there. I'll rewrite the code to only remove the attributes after the for loop is over as other browsers (besides Chrome) may also have this same behavior. Thanks for the helpful information.
