### ISSUE TITLE
How should we allow safeHTML

### ISSUE THREAD

**Issue by straker** [straker/html-tagged-template#15]
Currently any variable is safely encoded when placed inside a text node. However, we should definitely have someway for the user to mark that the HTML is trusted and that it should be rendered as DOM elements rather than text nodes. However we decided to do it, an attacker shouldn't be able to mark their own string as trusted (e.g. using an expression to do so).

**Comment by domenic** [comment]
I personally think this should be out of scope. People should have to manually manipulate the DOM with innerHTML to do this.

**Comment by straker** [comment]
I was hoping that with this new `html` tagged template function, we could deprecate the need for innerHTML. But it could still be useful if a user needs to save html to variables and render the variable as DOM.

**Comment by domenic** [comment]
Yeah. This is generally for replacing `x.innerHTML = '<p>foo...' + bar + '<i>stuff</i></p>'`, not for replacing `x.innerHTML = baz`.
