### ISSUE TITLE
Why not just use this library?

### ISSUE THREAD

**Issue by timwis** [straker/html-tagged-template#17]
Hey guys, forgive me if this is an obvious question, but why is this a "proposal" and not just a library? Can't developers just use this library and accomplish the "easier DOM element construction" you describe in the readme? It sounds like you're proposing it be native functionality within browsers, but why is that necessary? Is there something that you can't accomplish with tagged template literals? Or is it just not performant enough to do it that way?

**Comment by straker** [comment]
You are correct that you could just use this library to accomplish easier DOM element construction. But the same was true of jQuery 5 years ago when `element.querySelector` wasn't natively supported. The goal of this proposal is to further improve the JavaScript language so you don't need to bring in this library at all. Improving the DOM creation API has been in discussion for at least 5 years with the W3C, this proposal is the fruition of those discussions.

**Comment by straker** [comment]
Closeing
