### ISSUE TITLE
allow sub templates ?

### ISSUE THREAD

**Issue by kapouer** [straker/html-tagged-template#25]
I just got this case:
```
let me = html`<p>some text${insertImage(opts)}</p>`

function insertImage(opts) {
  if (opts.src) return html`<img src=${opts.src} />`
  else return '';
}
```
which will serialize the img node to `[object HTMLImageElement]`. Cannot it be properly html-serialized ?

**Comment by straker** [comment]
We had a [prior discussion](https://github.com/straker/html-tagged-template/issues/15) on allowing safe html insertion into the template string, and it was decided that html should still be inserted using current browser apis of `appendChild`, `insertHTML`, etc.

**Comment by kapouer** [comment]
Closing then.
