### ISSUE TITLE
allow values to be array of Nodes (or text), fragments

### ISSUE THREAD

**Issue by kapouer** [straker/html-tagged-template#29]
```
html`<div class="field" title="${schema.description || ''}">
	<label>${schema.title}</label>
	<select name="${key}" class="ui dropdown">
		${schema.oneOf.map(getSelectOption)}
	</select>
</div>`;
```
where getSelectOption returns a node, so the map returns an array of nodes.

**Comment by straker** [comment]
I'm not sure on this one. If you're using `map`, you could instead use `reduce` to change the array into a single string.

**Comment by kapouer** [comment]
Right, i thought for a moment we could have a marvelous template language right in the standard :)
But the fact template strings cannot be built from variables (without eval) is a no-go anyway.
